// Code generated by MockGen. DO NOT EDIT.
// Source: zizmor.go
//
// Generated by this command:
//
//	mockgen -source=zizmor.go -destination=zizmor_mock.go -package=zizmor Zizmor
//

// Package zizmor is a generated GoMock package.
package zizmor

import (
	context "context"
	reflect "reflect"
	dagger "workflow-scanner/internal/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockZizmor is a mock of Zizmor interface.
type MockZizmor struct {
	ctrl     *gomock.Controller
	recorder *MockZizmorMockRecorder
	isgomock struct{}
}

// MockZizmorMockRecorder is the mock recorder for MockZizmor.
type MockZizmorMockRecorder struct {
	mock *MockZizmor
}

// NewMockZizmor creates a new mock instance.
func NewMockZizmor(ctrl *gomock.Controller) *MockZizmor {
	mock := &MockZizmor{ctrl: ctrl}
	mock.recorder = &MockZizmorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZizmor) EXPECT() *MockZizmorMockRecorder {
	return m.recorder
}

// CheckRemainingIssues mocks base method.
func (m *MockZizmor) CheckRemainingIssues(ctx context.Context, source *dagger.Directory) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRemainingIssues", ctx, source)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRemainingIssues indicates an expected call of CheckRemainingIssues.
func (mr *MockZizmorMockRecorder) CheckRemainingIssues(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRemainingIssues", reflect.TypeOf((*MockZizmor)(nil).CheckRemainingIssues), ctx, source)
}

// RunZizmorAutoFix mocks base method.
func (m *MockZizmor) RunZizmorAutoFix(ctx context.Context, source *dagger.Directory) (*dagger.Directory, []Finding, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunZizmorAutoFix", ctx, source)
	ret0, _ := ret[0].(*dagger.Directory)
	ret1, _ := ret[1].([]Finding)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// RunZizmorAutoFix indicates an expected call of RunZizmorAutoFix.
func (mr *MockZizmorMockRecorder) RunZizmorAutoFix(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunZizmorAutoFix", reflect.TypeOf((*MockZizmor)(nil).RunZizmorAutoFix), ctx, source)
}

// ScanExternalDependencies mocks base method.
func (m *MockZizmor) ScanExternalDependencies(ctx context.Context, source *dagger.Directory) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanExternalDependencies", ctx, source)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanExternalDependencies indicates an expected call of ScanExternalDependencies.
func (mr *MockZizmorMockRecorder) ScanExternalDependencies(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanExternalDependencies", reflect.TypeOf((*MockZizmor)(nil).ScanExternalDependencies), ctx, source)
}

// SummarizeExternalFindings mocks base method.
func (m *MockZizmor) SummarizeExternalFindings(fullReport string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummarizeExternalFindings", fullReport)
	ret0, _ := ret[0].(string)
	return ret0
}

// SummarizeExternalFindings indicates an expected call of SummarizeExternalFindings.
func (mr *MockZizmorMockRecorder) SummarizeExternalFindings(fullReport any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummarizeExternalFindings", reflect.TypeOf((*MockZizmor)(nil).SummarizeExternalFindings), fullReport)
}
