version: 3

tasks:
  generate-dagger:
    cmds: 
      - |
        dagger develop --sdk=go --compat=skip
        cd workspace
        dagger develop --sdk=go --compat=skip
  mocks:
    cmds:
      - |
        go generate $(pwd)/pkg/dagger
        go generate $(pwd)/pkg/github
        go generate $(pwd)/pkg/zizmor
        go generate $(pwd)/pkg/agent
  setup:
    cmds:
      - task: generate-dagger
      - task: mocks
  # necessary for running tests out of vscode ui
  dotenv:
    cmds:
      - |
        echo "DAGGER_SESSION_PORT=123" > .env
        echo "DAGGER_SESSION_TOKEN=123" >> .env

  unit-tests:
    cmd: go test ./... -v run *_test.go

  tools:
    vars:
      DAGGER_VERSION: v0.19.6
    cmds: 
      - |
        if ! which dagger ; then
          echo "dagger not found, installing..."
          curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION={{ .DAGGER_VERSION }} BIN_DIR=$HOME/.local/bin sh
        fi
        go install go.uber.org/mock/mockgen@latest
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.2

  fmt:
    cmd: golangci-lint fmt ./...