// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/dagger/container.go
//
// Generated by this command:
//
//	mockgen -source=pkg/dagger/container.go -destination=tests/mocks/container_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dagger "dagger/workflow-scanner/internal/dagger"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainer is a mock of Container interface.
type MockContainer struct {
	ctrl     *gomock.Controller
	recorder *MockContainerMockRecorder
	isgomock struct{}
}

// MockContainerMockRecorder is the mock recorder for MockContainer.
type MockContainerMockRecorder struct {
	mock *MockContainer
}

// NewMockContainer creates a new mock instance.
func NewMockContainer(ctrl *gomock.Controller) *MockContainer {
	mock := &MockContainer{ctrl: ctrl}
	mock.recorder = &MockContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainer) EXPECT() *MockContainerMockRecorder {
	return m.recorder
}

// Directory mocks base method.
func (m *MockContainer) Directory(path string, opts ...dagger.ContainerDirectoryOpts) *dagger.Directory {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Directory", varargs...)
	ret0, _ := ret[0].(*dagger.Directory)
	return ret0
}

// Directory indicates an expected call of Directory.
func (mr *MockContainerMockRecorder) Directory(path any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Directory", reflect.TypeOf((*MockContainer)(nil).Directory), varargs...)
}

// From mocks base method.
func (m *MockContainer) From(address string) *dagger.Container {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "From", address)
	ret0, _ := ret[0].(*dagger.Container)
	return ret0
}

// From indicates an expected call of From.
func (mr *MockContainerMockRecorder) From(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "From", reflect.TypeOf((*MockContainer)(nil).From), address)
}

// Stdout mocks base method.
func (m *MockContainer) Stdout(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stdout", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stdout indicates an expected call of Stdout.
func (mr *MockContainerMockRecorder) Stdout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stdout", reflect.TypeOf((*MockContainer)(nil).Stdout), ctx)
}

// WithDirectory mocks base method.
func (m *MockContainer) WithDirectory(path string, source *dagger.Directory, opts ...dagger.ContainerWithDirectoryOpts) *dagger.Container {
	m.ctrl.T.Helper()
	varargs := []any{path, source}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithDirectory", varargs...)
	ret0, _ := ret[0].(*dagger.Container)
	return ret0
}

// WithDirectory indicates an expected call of WithDirectory.
func (mr *MockContainerMockRecorder) WithDirectory(path, source any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, source}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDirectory", reflect.TypeOf((*MockContainer)(nil).WithDirectory), varargs...)
}

// WithExec mocks base method.
func (m *MockContainer) WithExec(args []string, opts ...dagger.ContainerWithExecOpts) *dagger.Container {
	m.ctrl.T.Helper()
	varargs := []any{args}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithExec", varargs...)
	ret0, _ := ret[0].(*dagger.Container)
	return ret0
}

// WithExec indicates an expected call of WithExec.
func (mr *MockContainerMockRecorder) WithExec(args any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{args}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithExec", reflect.TypeOf((*MockContainer)(nil).WithExec), varargs...)
}

// WithWorkdir mocks base method.
func (m *MockContainer) WithWorkdir(path string, opts ...dagger.ContainerWithWorkdirOpts) *dagger.Container {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithWorkdir", varargs...)
	ret0, _ := ret[0].(*dagger.Container)
	return ret0
}

// WithWorkdir indicates an expected call of WithWorkdir.
func (mr *MockContainerMockRecorder) WithWorkdir(path any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWorkdir", reflect.TypeOf((*MockContainer)(nil).WithWorkdir), varargs...)
}
