// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/dagger/env.go
//
// Generated by this command:
//
//	mockgen -source=pkg/dagger/env.go -destination=tests/mocks/env_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dagger "dagger/workflow-scanner/internal/dagger"
	dagger0 "dagger/workflow-scanner/pkg/dagger"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnv is a mock of Env interface.
type MockEnv struct {
	ctrl     *gomock.Controller
	recorder *MockEnvMockRecorder
	isgomock struct{}
}

// MockEnvMockRecorder is the mock recorder for MockEnv.
type MockEnvMockRecorder struct {
	mock *MockEnv
}

// NewMockEnv creates a new mock instance.
func NewMockEnv(ctrl *gomock.Controller) *MockEnv {
	mock := &MockEnv{ctrl: ctrl}
	mock.recorder = &MockEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnv) EXPECT() *MockEnvMockRecorder {
	return m.recorder
}

// Output mocks base method.
func (m *MockEnv) Output(name string) dagger0.EnvOutput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Output", name)
	ret0, _ := ret[0].(dagger0.EnvOutput)
	return ret0
}

// Output indicates an expected call of Output.
func (mr *MockEnvMockRecorder) Output(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockEnv)(nil).Output), name)
}

// WithStringInput mocks base method.
func (m *MockEnv) WithStringInput(name, value, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStringInput", name, value, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithStringInput indicates an expected call of WithStringInput.
func (mr *MockEnvMockRecorder) WithStringInput(name, value, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStringInput", reflect.TypeOf((*MockEnv)(nil).WithStringInput), name, value, description)
}

// WithStringOutput mocks base method.
func (m *MockEnv) WithStringOutput(name, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStringOutput", name, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithStringOutput indicates an expected call of WithStringOutput.
func (mr *MockEnvMockRecorder) WithStringOutput(name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStringOutput", reflect.TypeOf((*MockEnv)(nil).WithStringOutput), name, description)
}

// WithWorkspaceInput mocks base method.
func (m *MockEnv) WithWorkspaceInput(name string, workspace dagger0.Workspace, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithWorkspaceInput", name, workspace, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithWorkspaceInput indicates an expected call of WithWorkspaceInput.
func (mr *MockEnvMockRecorder) WithWorkspaceInput(name, workspace, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWorkspaceInput", reflect.TypeOf((*MockEnv)(nil).WithWorkspaceInput), name, workspace, description)
}

// WithWorkspaceOutput mocks base method.
func (m *MockEnv) WithWorkspaceOutput(name, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithWorkspaceOutput", name, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithWorkspaceOutput indicates an expected call of WithWorkspaceOutput.
func (mr *MockEnvMockRecorder) WithWorkspaceOutput(name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWorkspaceOutput", reflect.TypeOf((*MockEnv)(nil).WithWorkspaceOutput), name, description)
}

// MockEnvOutput is a mock of EnvOutput interface.
type MockEnvOutput struct {
	ctrl     *gomock.Controller
	recorder *MockEnvOutputMockRecorder
	isgomock struct{}
}

// MockEnvOutputMockRecorder is the mock recorder for MockEnvOutput.
type MockEnvOutputMockRecorder struct {
	mock *MockEnvOutput
}

// NewMockEnvOutput creates a new mock instance.
func NewMockEnvOutput(ctrl *gomock.Controller) *MockEnvOutput {
	mock := &MockEnvOutput{ctrl: ctrl}
	mock.recorder = &MockEnvOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvOutput) EXPECT() *MockEnvOutputMockRecorder {
	return m.recorder
}

// AsString mocks base method.
func (m *MockEnvOutput) AsString(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsString", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AsString indicates an expected call of AsString.
func (mr *MockEnvOutputMockRecorder) AsString(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsString", reflect.TypeOf((*MockEnvOutput)(nil).AsString), ctx)
}

// AsWorkspace mocks base method.
func (m *MockEnvOutput) AsWorkspace() dagger0.Workspace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsWorkspace")
	ret0, _ := ret[0].(dagger0.Workspace)
	return ret0
}

// AsWorkspace indicates an expected call of AsWorkspace.
func (mr *MockEnvOutputMockRecorder) AsWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsWorkspace", reflect.TypeOf((*MockEnvOutput)(nil).AsWorkspace))
}

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
	isgomock struct{}
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockWorkspace) Source() *dagger.Directory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].(*dagger.Directory)
	return ret0
}

// Source indicates an expected call of Source.
func (mr *MockWorkspaceMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockWorkspace)(nil).Source))
}

// MockCurrentModule is a mock of CurrentModule interface.
type MockCurrentModule struct {
	ctrl     *gomock.Controller
	recorder *MockCurrentModuleMockRecorder
	isgomock struct{}
}

// MockCurrentModuleMockRecorder is the mock recorder for MockCurrentModule.
type MockCurrentModuleMockRecorder struct {
	mock *MockCurrentModule
}

// NewMockCurrentModule creates a new mock instance.
func NewMockCurrentModule(ctrl *gomock.Controller) *MockCurrentModule {
	mock := &MockCurrentModule{ctrl: ctrl}
	mock.recorder = &MockCurrentModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrentModule) EXPECT() *MockCurrentModuleMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockCurrentModule) Source() dagger0.ModuleSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].(dagger0.ModuleSource)
	return ret0
}

// Source indicates an expected call of Source.
func (mr *MockCurrentModuleMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockCurrentModule)(nil).Source))
}

// MockModuleSource is a mock of ModuleSource interface.
type MockModuleSource struct {
	ctrl     *gomock.Controller
	recorder *MockModuleSourceMockRecorder
	isgomock struct{}
}

// MockModuleSourceMockRecorder is the mock recorder for MockModuleSource.
type MockModuleSourceMockRecorder struct {
	mock *MockModuleSource
}

// NewMockModuleSource creates a new mock instance.
func NewMockModuleSource(ctrl *gomock.Controller) *MockModuleSource {
	mock := &MockModuleSource{ctrl: ctrl}
	mock.recorder = &MockModuleSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleSource) EXPECT() *MockModuleSourceMockRecorder {
	return m.recorder
}

// File mocks base method.
func (m *MockModuleSource) File(path string) *dagger.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File", path)
	ret0, _ := ret[0].(*dagger.File)
	return ret0
}

// File indicates an expected call of File.
func (mr *MockModuleSourceMockRecorder) File(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockModuleSource)(nil).File), path)
}

// MockLLM is a mock of LLM interface.
type MockLLM struct {
	ctrl     *gomock.Controller
	recorder *MockLLMMockRecorder
	isgomock struct{}
}

// MockLLMMockRecorder is the mock recorder for MockLLM.
type MockLLMMockRecorder struct {
	mock *MockLLM
}

// NewMockLLM creates a new mock instance.
func NewMockLLM(ctrl *gomock.Controller) *MockLLM {
	mock := &MockLLM{ctrl: ctrl}
	mock.recorder = &MockLLMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLM) EXPECT() *MockLLMMockRecorder {
	return m.recorder
}

// WithEnv mocks base method.
func (m *MockLLM) WithEnv(env dagger0.Env) dagger0.LLMWithEnv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithEnv", env)
	ret0, _ := ret[0].(dagger0.LLMWithEnv)
	return ret0
}

// WithEnv indicates an expected call of WithEnv.
func (mr *MockLLMMockRecorder) WithEnv(env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithEnv", reflect.TypeOf((*MockLLM)(nil).WithEnv), env)
}

// WithPromptFile mocks base method.
func (m *MockLLM) WithPromptFile(file *dagger.File) dagger0.LLMWithEnv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithPromptFile", file)
	ret0, _ := ret[0].(dagger0.LLMWithEnv)
	return ret0
}

// WithPromptFile indicates an expected call of WithPromptFile.
func (mr *MockLLMMockRecorder) WithPromptFile(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPromptFile", reflect.TypeOf((*MockLLM)(nil).WithPromptFile), file)
}

// MockLLMWithEnv is a mock of LLMWithEnv interface.
type MockLLMWithEnv struct {
	ctrl     *gomock.Controller
	recorder *MockLLMWithEnvMockRecorder
	isgomock struct{}
}

// MockLLMWithEnvMockRecorder is the mock recorder for MockLLMWithEnv.
type MockLLMWithEnvMockRecorder struct {
	mock *MockLLMWithEnv
}

// NewMockLLMWithEnv creates a new mock instance.
func NewMockLLMWithEnv(ctrl *gomock.Controller) *MockLLMWithEnv {
	mock := &MockLLMWithEnv{ctrl: ctrl}
	mock.recorder = &MockLLMWithEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMWithEnv) EXPECT() *MockLLMWithEnvMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *MockLLMWithEnv) Env() dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockLLMWithEnvMockRecorder) Env() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockLLMWithEnv)(nil).Env))
}

// WithEnv mocks base method.
func (m *MockLLMWithEnv) WithEnv(env dagger0.Env) dagger0.LLMWithEnv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithEnv", env)
	ret0, _ := ret[0].(dagger0.LLMWithEnv)
	return ret0
}

// WithEnv indicates an expected call of WithEnv.
func (mr *MockLLMWithEnvMockRecorder) WithEnv(env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithEnv", reflect.TypeOf((*MockLLMWithEnv)(nil).WithEnv), env)
}

// WithPromptFile mocks base method.
func (m *MockLLMWithEnv) WithPromptFile(file *dagger.File) dagger0.LLMWithEnv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithPromptFile", file)
	ret0, _ := ret[0].(dagger0.LLMWithEnv)
	return ret0
}

// WithPromptFile indicates an expected call of WithPromptFile.
func (mr *MockLLMWithEnvMockRecorder) WithPromptFile(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPromptFile", reflect.TypeOf((*MockLLMWithEnv)(nil).WithPromptFile), file)
}
