// Code generated by MockGen. DO NOT EDIT.
// Source: agent.go
//
// Generated by this command:
//
//	mockgen -source=agent.go -destination=../../mocks/agent_mock.go -package=mocks Agent
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dagger "workflow-scanner/internal/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// FixRemainingIssues mocks base method.
func (m *MockAgent) FixRemainingIssues(ctx context.Context, source *dagger.Directory, issues string) (*dagger.Directory, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FixRemainingIssues", ctx, source, issues)
	ret0, _ := ret[0].(*dagger.Directory)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FixRemainingIssues indicates an expected call of FixRemainingIssues.
func (mr *MockAgentMockRecorder) FixRemainingIssues(ctx, source, issues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FixRemainingIssues", reflect.TypeOf((*MockAgent)(nil).FixRemainingIssues), ctx, source, issues)
}
