// Code generated by MockGen. DO NOT EDIT.
// Source: binding.go
//
// Generated by this command:
//
//	mockgen -source=binding.go -destination=../../mocks/binding_mock.go -package=mocks Binding
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dagger "dagger/workflow-scanner/pkg/dagger"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBinding is a mock of Binding interface.
type MockBinding struct {
	ctrl     *gomock.Controller
	recorder *MockBindingMockRecorder
	isgomock struct{}
}

// MockBindingMockRecorder is the mock recorder for MockBinding.
type MockBindingMockRecorder struct {
	mock *MockBinding
}

// NewMockBinding creates a new mock instance.
func NewMockBinding(ctrl *gomock.Controller) *MockBinding {
	mock := &MockBinding{ctrl: ctrl}
	mock.recorder = &MockBindingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinding) EXPECT() *MockBindingMockRecorder {
	return m.recorder
}

// AsString mocks base method.
func (m *MockBinding) AsString(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsString", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AsString indicates an expected call of AsString.
func (mr *MockBindingMockRecorder) AsString(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsString", reflect.TypeOf((*MockBinding)(nil).AsString), ctx)
}

// AsWorkspace mocks base method.
func (m *MockBinding) AsWorkspace() dagger.Workspace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsWorkspace")
	ret0, _ := ret[0].(dagger.Workspace)
	return ret0
}

// AsWorkspace indicates an expected call of AsWorkspace.
func (mr *MockBindingMockRecorder) AsWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsWorkspace", reflect.TypeOf((*MockBinding)(nil).AsWorkspace))
}
