// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../../mocks/client_mock.go -package=mocks Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dagger "workflow-scanner/internal/dagger"
	dagger0 "workflow-scanner/pkg/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Container mocks base method.
func (m *MockClient) Container(opts ...dagger.ContainerOpts) dagger0.Container {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Container", varargs...)
	ret0, _ := ret[0].(dagger0.Container)
	return ret0
}

// Container indicates an expected call of Container.
func (mr *MockClientMockRecorder) Container(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Container", reflect.TypeOf((*MockClient)(nil).Container), opts...)
}

// CurrentModule mocks base method.
func (m *MockClient) CurrentModule() dagger0.CurrentModule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentModule")
	ret0, _ := ret[0].(dagger0.CurrentModule)
	return ret0
}

// CurrentModule indicates an expected call of CurrentModule.
func (mr *MockClientMockRecorder) CurrentModule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentModule", reflect.TypeOf((*MockClient)(nil).CurrentModule))
}

// Env mocks base method.
func (m *MockClient) Env(opts ...dagger.EnvOpts) dagger0.Env {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Env", varargs...)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockClientMockRecorder) Env(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockClient)(nil).Env), opts...)
}

// LLM mocks base method.
func (m *MockClient) LLM(opts ...dagger.LLMOpts) dagger0.LLM {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LLM", varargs...)
	ret0, _ := ret[0].(dagger0.LLM)
	return ret0
}

// LLM indicates an expected call of LLM.
func (mr *MockClientMockRecorder) LLM(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LLM", reflect.TypeOf((*MockClient)(nil).LLM), opts...)
}

// Workspace mocks base method.
func (m *MockClient) Workspace(source *dagger.Directory) dagger0.Workspace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Workspace", source)
	ret0, _ := ret[0].(dagger0.Workspace)
	return ret0
}

// Workspace indicates an expected call of Workspace.
func (mr *MockClientMockRecorder) Workspace(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Workspace", reflect.TypeOf((*MockClient)(nil).Workspace), source)
}
