// Code generated by MockGen. DO NOT EDIT.
// Source: currentModule.go
//
// Generated by this command:
//
//	mockgen -source=currentModule.go -destination=../../mocks/currentModule_mock.go -package=mocks CurrentModule
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dagger "workflow-scanner/pkg/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockCurrentModule is a mock of CurrentModule interface.
type MockCurrentModule struct {
	ctrl     *gomock.Controller
	recorder *MockCurrentModuleMockRecorder
	isgomock struct{}
}

// MockCurrentModuleMockRecorder is the mock recorder for MockCurrentModule.
type MockCurrentModuleMockRecorder struct {
	mock *MockCurrentModule
}

// NewMockCurrentModule creates a new mock instance.
func NewMockCurrentModule(ctrl *gomock.Controller) *MockCurrentModule {
	mock := &MockCurrentModule{ctrl: ctrl}
	mock.recorder = &MockCurrentModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrentModule) EXPECT() *MockCurrentModuleMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockCurrentModule) Source() dagger.Directory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].(dagger.Directory)
	return ret0
}

// Source indicates an expected call of Source.
func (mr *MockCurrentModuleMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockCurrentModule)(nil).Source))
}
