// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dagger/dagger.gen.go
//
// Generated by this command:
//
//	mockgen -source=internal/dagger/dagger.gen.go -destination=tests/mocks/dagger_internal_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockextendedError is a mock of extendedError interface.
type MockextendedError struct {
	ctrl     *gomock.Controller
	recorder *MockextendedErrorMockRecorder
	isgomock struct{}
}

// MockextendedErrorMockRecorder is the mock recorder for MockextendedError.
type MockextendedErrorMockRecorder struct {
	mock *MockextendedError
}

// NewMockextendedError creates a new mock instance.
func NewMockextendedError(ctrl *gomock.Controller) *MockextendedError {
	mock := &MockextendedError{ctrl: ctrl}
	mock.recorder = &MockextendedErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockextendedError) EXPECT() *MockextendedErrorMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockextendedError) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockextendedErrorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockextendedError)(nil).Error))
}

// Extensions mocks base method.
func (m *MockextendedError) Extensions() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extensions")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Extensions indicates an expected call of Extensions.
func (mr *MockextendedErrorMockRecorder) Extensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extensions", reflect.TypeOf((*MockextendedError)(nil).Extensions))
}
