// Code generated by MockGen. DO NOT EDIT.
// Source: directory.go
//
// Generated by this command:
//
//	mockgen -source=directory.go -destination=../../mocks/directory_mock.go -package=mocks Directory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dagger "workflow-scanner/internal/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockDirectory is a mock of Directory interface.
type MockDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryMockRecorder
	isgomock struct{}
}

// MockDirectoryMockRecorder is the mock recorder for MockDirectory.
type MockDirectoryMockRecorder struct {
	mock *MockDirectory
}

// NewMockDirectory creates a new mock instance.
func NewMockDirectory(ctrl *gomock.Controller) *MockDirectory {
	mock := &MockDirectory{ctrl: ctrl}
	mock.recorder = &MockDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectory) EXPECT() *MockDirectoryMockRecorder {
	return m.recorder
}

// File mocks base method.
func (m *MockDirectory) File(path string) *dagger.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File", path)
	ret0, _ := ret[0].(*dagger.File)
	return ret0
}

// File indicates an expected call of File.
func (mr *MockDirectoryMockRecorder) File(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockDirectory)(nil).File), path)
}
