// Code generated by MockGen. DO NOT EDIT.
// Source: env.go
//
// Generated by this command:
//
//	mockgen -source=env.go -destination=../../mocks/env_mock.go -package=mocks Env
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dagger "dagger/workflow-scanner/internal/dagger"
	dagger0 "dagger/workflow-scanner/pkg/dagger"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnv is a mock of Env interface.
type MockEnv struct {
	ctrl     *gomock.Controller
	recorder *MockEnvMockRecorder
	isgomock struct{}
}

// MockEnvMockRecorder is the mock recorder for MockEnv.
type MockEnvMockRecorder struct {
	mock *MockEnv
}

// NewMockEnv creates a new mock instance.
func NewMockEnv(ctrl *gomock.Controller) *MockEnv {
	mock := &MockEnv{ctrl: ctrl}
	mock.recorder = &MockEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnv) EXPECT() *MockEnvMockRecorder {
	return m.recorder
}

// GetEnv mocks base method.
func (m *MockEnv) GetEnv() *dagger.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnv")
	ret0, _ := ret[0].(*dagger.Env)
	return ret0
}

// GetEnv indicates an expected call of GetEnv.
func (mr *MockEnvMockRecorder) GetEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnv", reflect.TypeOf((*MockEnv)(nil).GetEnv))
}

// Output mocks base method.
func (m *MockEnv) Output(name string) dagger0.Binding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Output", name)
	ret0, _ := ret[0].(dagger0.Binding)
	return ret0
}

// Output indicates an expected call of Output.
func (mr *MockEnvMockRecorder) Output(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockEnv)(nil).Output), name)
}

// WithStringInput mocks base method.
func (m *MockEnv) WithStringInput(name, value, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStringInput", name, value, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithStringInput indicates an expected call of WithStringInput.
func (mr *MockEnvMockRecorder) WithStringInput(name, value, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStringInput", reflect.TypeOf((*MockEnv)(nil).WithStringInput), name, value, description)
}

// WithStringOutput mocks base method.
func (m *MockEnv) WithStringOutput(name, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStringOutput", name, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithStringOutput indicates an expected call of WithStringOutput.
func (mr *MockEnvMockRecorder) WithStringOutput(name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStringOutput", reflect.TypeOf((*MockEnv)(nil).WithStringOutput), name, description)
}

// WithWorkspaceInput mocks base method.
func (m *MockEnv) WithWorkspaceInput(name string, value dagger0.Workspace, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithWorkspaceInput", name, value, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithWorkspaceInput indicates an expected call of WithWorkspaceInput.
func (mr *MockEnvMockRecorder) WithWorkspaceInput(name, value, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWorkspaceInput", reflect.TypeOf((*MockEnv)(nil).WithWorkspaceInput), name, value, description)
}

// WithWorkspaceOutput mocks base method.
func (m *MockEnv) WithWorkspaceOutput(name, description string) dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithWorkspaceOutput", name, description)
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// WithWorkspaceOutput indicates an expected call of WithWorkspaceOutput.
func (mr *MockEnvMockRecorder) WithWorkspaceOutput(name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithWorkspaceOutput", reflect.TypeOf((*MockEnv)(nil).WithWorkspaceOutput), name, description)
}
