// Code generated by MockGen. DO NOT EDIT.
// Source: wrapper.go
//
// Generated by this command:
//
//	mockgen -source=wrapper.go -destination=../../mocks/github_wrapper_mock.go -package=mocks WrapperIssueClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dagger "workflow-scanner/internal/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockWrapperIssueClient is a mock of WrapperIssueClient interface.
type MockWrapperIssueClient struct {
	ctrl     *gomock.Controller
	recorder *MockWrapperIssueClientMockRecorder
	isgomock struct{}
}

// MockWrapperIssueClientMockRecorder is the mock recorder for MockWrapperIssueClient.
type MockWrapperIssueClientMockRecorder struct {
	mock *MockWrapperIssueClient
}

// NewMockWrapperIssueClient creates a new mock instance.
func NewMockWrapperIssueClient(ctrl *gomock.Controller) *MockWrapperIssueClient {
	mock := &MockWrapperIssueClient{ctrl: ctrl}
	mock.recorder = &MockWrapperIssueClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWrapperIssueClient) EXPECT() *MockWrapperIssueClientMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockWrapperIssueClient) CreatePullRequest(ctx context.Context, repo, title, body string, source *dagger.Directory, targetBranch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, repo, title, body, source, targetBranch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockWrapperIssueClientMockRecorder) CreatePullRequest(ctx, repo, title, body, source, targetBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockWrapperIssueClient)(nil).CreatePullRequest), ctx, repo, title, body, source, targetBranch)
}
