// Code generated by MockGen. DO NOT EDIT.
// Source: llm.go
//
// Generated by this command:
//
//	mockgen -source=llm.go -destination=../../mocks/llm_mock.go -package=mocks LLM
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dagger "workflow-scanner/internal/dagger"
	dagger0 "workflow-scanner/pkg/dagger"

	gomock "go.uber.org/mock/gomock"
)

// MockLLM is a mock of LLM interface.
type MockLLM struct {
	ctrl     *gomock.Controller
	recorder *MockLLMMockRecorder
	isgomock struct{}
}

// MockLLMMockRecorder is the mock recorder for MockLLM.
type MockLLMMockRecorder struct {
	mock *MockLLM
}

// NewMockLLM creates a new mock instance.
func NewMockLLM(ctrl *gomock.Controller) *MockLLM {
	mock := &MockLLM{ctrl: ctrl}
	mock.recorder = &MockLLMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLM) EXPECT() *MockLLMMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *MockLLM) Env() dagger0.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(dagger0.Env)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockLLMMockRecorder) Env() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockLLM)(nil).Env))
}

// LastReply mocks base method.
func (m *MockLLM) LastReply(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastReply", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastReply indicates an expected call of LastReply.
func (mr *MockLLMMockRecorder) LastReply(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastReply", reflect.TypeOf((*MockLLM)(nil).LastReply), ctx)
}

// WithEnv mocks base method.
func (m *MockLLM) WithEnv(env dagger0.Env) dagger0.LLM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithEnv", env)
	ret0, _ := ret[0].(dagger0.LLM)
	return ret0
}

// WithEnv indicates an expected call of WithEnv.
func (mr *MockLLMMockRecorder) WithEnv(env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithEnv", reflect.TypeOf((*MockLLM)(nil).WithEnv), env)
}

// WithPromptFile mocks base method.
func (m *MockLLM) WithPromptFile(file *dagger.File) dagger0.LLM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithPromptFile", file)
	ret0, _ := ret[0].(dagger0.LLM)
	return ret0
}

// WithPromptFile indicates an expected call of WithPromptFile.
func (mr *MockLLMMockRecorder) WithPromptFile(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPromptFile", reflect.TypeOf((*MockLLM)(nil).WithPromptFile), file)
}
