package main

import (
	"context"

	"dagger/workflow-scanner/internal/dagger"
)

type WorkflowScanner struct{}

// Scan GitHub Actions workflows for security vulnerabilities and create a PR with fixes
func (m *WorkflowScanner) ScanAndFixWorkflows(
	ctx context.Context,
	// Github Token with permissions to write issues and contents
	githubToken *dagger.Secret,
	// Github repository url
	repository string,
	// +defaultPath="/"
	source *dagger.Directory,
) (string, error) {
	// Environment with agent inputs and outputs
	environment := dag.Env().
		WithWorkspaceInput(
			"workspace",
			dag.Workspace(source),
			"the workspace containing GitHub Actions workflows to scan").
		WithWorkspaceOutput(
			"completed",
			"the workspace with security vulnerabilities fixed")

	// Security scanning prompt stored in markdown file
	promptFile := dag.CurrentModule().Source().File("simple_scan_prompt.md")

	// Put it all together to form the security agent
	work := dag.LLM().
		WithEnv(environment).
		WithPromptFile(promptFile)

	// Get the output from the security agent
	completed := work.
		Env().
		Output("completed").
		AsWorkspace()
	completedDirectory := completed.Source().WithoutDirectory("node_modules")

	// Create GitHub client for PR operations
	issueClient := dag.GithubIssue(dagger.GithubIssueOpts{Token: githubToken})
	
	// Create pull request with security fixes
	title := "Security fixes for GitHub Actions workflows"
	body := "This PR contains automated security fixes for GitHub Actions workflows.\n\n This PR was automatically generated by a security scanning agent."
	
	pr := issueClient.CreatePullRequest(repository, title, body, completedDirectory)

	return pr.URL(ctx)
}