name: Run qualification on branch

on:
  push:
    branches-ignore:
      - main

jobs:
  lint-fmt:
    name: Lint & Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4.1.1 (2024-03-05)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
    
      - name: Setup Go
        # v5.0.1 (2024-04-25)
        uses: actions/setup-go@3c54f80349a9fd31e1f4347225c80f3f799dbb11
        with:
          go-version: 1.25.3

      - name: Install Task
        # TODO: Pin this action to a commit SHA - visit https://github.com/go-task/setup-task/releases to find the hash
        uses: go-task/setup-task@v1

      - name: Install golangci-lint
        # TODO: Pin this action to a commit SHA - visit https://github.com/golangci/golangci-lint-action/releases to find the hash
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6.2
          install-mode: binary
          install-only: true

      - name: Lint
        run: task lint

      - name: Format
        if: always()
        run: task fmt

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4.1.1 (2024-03-05)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
    
      - name: Setup Go
        # v5.0.1 (2024-04-25)
        uses: actions/setup-go@3c54f80349a9fd31e1f4347225c80f3f799dbb11
        with:
          go-version: 1.25.3

      - name: Install Task
        # TODO: Pin this action to a commit SHA - visit https://github.com/go-task/setup-task/releases to find the hash
        uses: go-task/setup-task@v1

      - name: Install mockgen
        run: task install-mockgen

      - name: Generate main dagger code
        # TODO: Pin this action to a commit SHA - visit https://github.com/dagger/dagger-for-github/releases to find the hash
        uses: dagger/dagger-for-github@v8.2.0
        with:
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate workspace dagger code
        # TODO: Pin this action to a commit SHA - visit https://github.com/dagger/dagger-for-github/releases to find the hash
        uses: dagger/dagger-for-github@v8.2.0
        with:
            workdir: workspace
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate mocks
        run: task mocks

      - name: Run tests with task
        run: task unit-tests

  security:
    name: Security checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4.1.1 (2024-03-05)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
    
      - name: Setup Go
        # v5.0.1 (2024-04-25)
        uses: actions/setup-go@3c54f80349a9fd31e1f4347225c80f3f799dbb11
        with:
          go-version: 1.25.3

      # use go install and run task, does not seem to properly exclude generated dagger code
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Install Task
        # TODO: Pin this action to a commit SHA - visit https://github.com/go-task/setup-task/releases to find the hash
        uses: go-task/setup-task@v1

      - name: Install mockgen
        run: task install-mockgen

      - name: Generate main dagger code
        # TODO: Pin this action to a commit SHA - visit https://github.com/dagger/dagger-for-github/releases to find the hash
        uses: dagger/dagger-for-github@v8.2.0
        with:
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate workspace dagger code
        # TODO: Pin this action to a commit SHA - visit https://github.com/dagger/dagger-for-github/releases to find the hash
        uses: dagger/dagger-for-github@v8.2.0
        with:
            workdir: workspace
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate mocks
        run: task mocks

      - name: Run gosec
        run: task gosec
