name: Run qualification on branch

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  lint-fmt:
    name: Lint & Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.3.4
        with:
          persist-credentials: false
    
      - name: Setup Go
        uses: actions/setup-go@b4ffde65f46336ab88eb53be808477a3936bae11  # v5.0.0
        with:
          go-version: 1.25.3

      - name: Install Task
        uses: go-task/setup-task@b4ffde65f46336ab88eb53be808477a3936bae11  # v1.0.0

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.6.2
        with:
          version: v2.6.2
          install-mode: binary
          install-only: true

      - name: Lint
        run: task lint

      - name: Format
        if: always()
        run: task fmt

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.3.4
        with:
          persist-credentials: false
    
      - name: Setup Go
        uses: actions/setup-go@b4ffde65f46336ab88eb53be808477a3936bae11  # v5.0.0
        with:
          go-version: 1.25.3

      - name: Install Task
        uses: go-task/setup-task@b4ffde65f46336ab88eb53be808477a3936bae11  # v1.0.0

      - name: Install mockgen
        run: task install-mockgen

      - name: Generate main dagger code
        uses: dagger/dagger-for-github@b4ffde65f46336ab88eb53be808477a3936bae11  # v8.2.0
        with:
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate workspace dagger code
        uses: dagger/dagger-for-github@b4ffde65f46336ab88eb53be808477a3936bae11  # v8.2.0
        with:
            workdir: workspace
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate mocks
        run: task mocks

      - name: Run tests with task
        run: task unit-tests

  security:
    name: Security checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.3.4
        with:
          persist-credentials: false
    
      - name: Setup Go
        uses: actions/setup-go@b4ffde65f46336ab88eb53be808477a3936bae11  # v5.0.0
        with:
          go-version: 1.25.3

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Install Task
        uses: go-task/setup-task@b4ffde65f46336ab88eb53be808477a3936bae11  # v1.0.0

      - name: Install mockgen
        run: task install-mockgen

      - name: Generate main dagger code
        uses: dagger/dagger-for-github@b4ffde65f46336ab88eb53be808477a3936bae11  # v8.2.0
        with:
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate workspace dagger code
        uses: dagger/dagger-for-github@b4ffde65f46336ab88eb53be808477a3936bae11  # v8.2.0
        with:
            workdir: workspace
            verb: develop
            args: --sdk=go --compat=skip
            version: "v0.19.6"

      - name: Generate mocks
        run: task mocks

      - name: Run gosec
        run: task gosec
