name: Build and Deploy

on:
  push:
    branches:
      - main

permissions: none

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.4.0
        with:
          persist-credentials: false
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.0.0
      
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.0.0
      
      - name: Build Docker Image
        uses: docker/build-push-action@b4ffde65f46336ab88eb53be808477a3936bae11  # v3.0.0
        with:
          context: .
          push: true
          tags: user/app:latest
