name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Output semver
        id: get_bump
        run: |
          if [[ "$(echo ${{ join(github.event.pull_request.labels.*.name, '|') }} | grep -Po "semver-(major|minor|patch)" | wc -l)" -gt 1 ]]; then
            echo "More than 1 semver tag found: ${semver}"
            exit 1
          fi
          echo "bump=${semver}" | sed 's/semver-//g' >> $GITHUB_OUTPUT
      - name: Tag the release
        # TODO: Pin this action to a commit SHA for security
        uses: anothrNick/github-tag-action@v1
