name: Main Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.3.4

      - name: Output semver
        id: get_bump
        run: |
          if [[ "$(echo ${{ join(github.event.pull_request.labels.*.name, '|') }} | grep -Po "semver-(major|minor|patch)" | wc -l)" -gt 1 ]]; then
              echo "More than 1 semver tag found: ${semver}"
              exit 1
          fi
          echo "bump=${semver}" | sed 's/semver-//g' >> $GITHUB_OUTPUT

      - name: Tag Release
        uses: anothrNick/github-tag-action@b4ffde65f46336ab88eb53be808477a3936bae11  # v1.0.0
