name: Workflow Scanner

on:
  push:
    branches:
      - main

jobs:
  test-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v2.4.0

      - name: Run scanner
        uses: docker/login-action@b4ffde65f46336ab88eb53be808477a3936bae11  # v3.0.0

      - name: Run custom scanner
        uses: Scalabit/workflow-scanner-action@b4ffde65f46336ab88eb53be808477a3936bae11  # v1.0.0
